### ISSUE TITLE
Error when running docker container

### ISSUE THREAD

**Issue by MaObOriginal** [numberly/mattermost-integration-giphy#27]
Hey!

Get this error when I want to start the docker container:
Andy Ideas?

My Docker run command looks ,ike this:
docker run -d -e autostart=true --restart always --name mattermost-giphy -p 5000:5000 -e MATTERMOST_GIPHY_TOKEN=7hwb9c7hapb8dexsryciexoh1a -e MATTERMOST_GIPHY_HOST=IP-ADRESS -e MATTERMOST_GIPHY_PORT=5000 -e GIPHY_API_KEY=dc6zaTOxFJmzC mattermost-integration-giphy

`Traceback (most recent call last):
  File "run.py", line 20, in <module>
    app.run(host=str(host), port=int(port))
  File "/usr/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/site-packages/Werkzeug-0.12.2-py2.7.egg/werkzeug/serving.py", line 739, in run_simple
    inner()
  File "/usr/local/lib/python2.7/site-packages/Werkzeug-0.12.2-py2.7.egg/werkzeug/serving.py", line 699, in inner
    fd=fd)
  File "/usr/local/lib/python2.7/site-packages/Werkzeug-0.12.2-py2.7.egg/werkzeug/serving.py", line 593, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/usr/local/lib/python2.7/site-packages/Werkzeug-0.12.2-py2.7.egg/werkzeug/serving.py", line 504, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/local/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/local/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Address not available`

**Comment by trubesv** [comment]
`ADDRESS` au lieu de `ADRESS`?

**Comment by MaObOriginal** [comment]
It's a placeholder. The Ip-Address ist correct

**Comment by pichouk** [comment]
@starmagoo What did you put on the address field ? Usually `0.0.0.0` (default value) is better, it allow you to listen on all interfaces.

**Comment by MaObOriginal** [comment]
I put the external IP-Adress of my server in the address field. I will try "0.0.0.0".

**Comment by MaObOriginal** [comment]
Worked! Thanks a lot.

**Comment by pichouk** [comment]
Actually this variable is a little bit useless when you run Mattermost Giphy inside a container.

Your container only see 2 addresses : `127.0.0.1` and your container addr (something like `172.X.X.X` with Docker). It doesn't know your host IP so trying to listening on your host IP will not work.

2 solutions : 
- use `0.0.0.0` so your container will listen on all addresses
- run your container with "host network" enable allowing your container to share your host network interfaces. But I don't see any benefit in that case.
