### ISSUE TITLE
Issue when running run.py

### ISSUE THREAD

**Issue by krisgermann** [numberly/mattermost-integration-giphy#28]
I am following the instructions  (https://github.com/numberly/mattermost-integration-giphy/blob/master/LINUX.md) but get the following error when I run "python run.py"

Running Ubuntu 16.04.3 LTS

Traceback (most recent call last):
  File "run.py", line 20, in <module>
    app.run(host=str(host), port=int(port))
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/dist-packages/Werkzeug-0.13-py2.7.egg/werkzeug/serving.py", line 799, in run_simple
    inner()
  File "/usr/local/lib/python2.7/dist-packages/Werkzeug-0.13-py2.7.egg/werkzeug/serving.py", line 759, in inner
    fd=fd)
  File "/usr/local/lib/python2.7/dist-packages/Werkzeug-0.13-py2.7.egg/werkzeug/serving.py", line 651, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/usr/local/lib/python2.7/dist-packages/Werkzeug-0.13-py2.7.egg/werkzeug/serving.py", line 562, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address

**Comment by ramnes** [comment]
Hi @krisgermann.

Here, Python is telling you here that the port on which it's trying to listen is already used by another process.

As stated in the documentation you linked, mattermost-integration-giphy uses TCP port 5000 by default but you can change that value with the environment variable `MATTERMOST_GIPHY_PORT`.

You can list all the TCP ports actually in use with `sudo netstats -lpnt` (in the "Local Address" column).

Does that help?

**Comment by krisgermann** [comment]
Oddly enough, 5000 isn't in use:

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      2584/nginx -g daemo
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      742/mysqld      
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      2584/nginx -g daemo
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      692/sshd        
tcp6       0      0 :::8065                 :::*                    LISTEN      2280/platform   
tcp6       0      0 :::22                   :::*                    LISTEN      692/sshd      

I do not have ~/.bash_profile so I used ~/.profile, is that an issue?

root@chat:~/mattermost-integration-giphy# cat ~/.profile 
# ~/.profile: executed by Bourne-compatible login shells.

if [ "$BASH" ]; then
  if [ -f ~/.bashrc ]; then
    . ~/.bashrc
  fi
fi

export MATTERMOST_GIPHY_TOKEN=qnypx8opftrwpr9xbqwebhepia
export MATTERMOST_GIPHY_HOST=mattermostURL
export MATTERMOST_GIPHY_PORT=5000

mesg n || true

**Comment by ramnes** [comment]
Oh, sorry, I misread. If the port was already in use, you would have had an "Address already in use" error, not this.

Just remove your `MATTERMOST_GIPHY_HOST` line. Unless you really know what you're doing, you want to use 0.0.0.0, which is already the default.

**Comment by krisgermann** [comment]
No problem at all!

After removing the "MATTERMOST_GIPHY_HOST line I get the same error, though.

# ~/.profile: executed by Bourne-compatible login shells.

if [ "$BASH" ]; then
  if [ -f ~/.bashrc ]; then
    . ~/.bashrc
  fi
fi

#export MATTERMOST_GIPHY_HOST=localhost
export MATTERMOST_GIPHY_TOKEN=qnypx8opftrwpr9xbqwebhepia
export MATTERMOST_GIPHY_PORT=5000

mesg n || true

Error:

Traceback (most recent call last):
  File "run.py", line 20, in <module>
    app.run(host=str(host), port=int(port))
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/dist-packages/Werkzeug-0.13-py2.7.egg/werkzeug/serving.py", line 799, in run_simple
    inner()
  File "/usr/local/lib/python2.7/dist-packages/Werkzeug-0.13-py2.7.egg/werkzeug/serving.py", line 759, in inner
    fd=fd)
  File "/usr/local/lib/python2.7/dist-packages/Werkzeug-0.13-py2.7.egg/werkzeug/serving.py", line 651, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/usr/local/lib/python2.7/dist-packages/Werkzeug-0.13-py2.7.egg/werkzeug/serving.py", line 562, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address

I have also tried to comment out the MATTERMOST_GIPHY_PORT as it's specified in the run.py script as well, but I get the same error.

**Comment by ramnes** [comment]
`unset MATTERMOST_GIPHY_HOST` and try again, maybe? :roll_eyes:

**Comment by krisgermann** [comment]
That one worked!

Thanks for all the help @ramnes :)
